name: Deploy To AWS using CDK

on:
  push:
    tags: cdk-*
env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: ${{ vars.ACCOUNT_AWS_ROLE_ARN }}

jobs:
  ci:
    name: Deploy To AWS using CDK
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for aws-actions/configure-aws-credentials
      contents: read # for actions/checkout
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ env.AWS_ROLE_ARN }}
            role-session-name: DeployRoleForGitHubSession
            aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
            node-version: 20.x
            cache: 'npm'

      - run: | 
          npm --prefix cdk run install
          npm --prefix cdk run cdk deploy --require-approval never
