name: Deploy To AWS using CDK

on:
  push:
    branches: 
      - 'cdk-*'        # Production branches
      - 'cdk-dev-*'    # Development branches
    tags: cdk-*
concurrency: 
  group: deploy-cdk
  cancel-in-progress: false
env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: ${{ vars.ACCOUNT_AWS_ROLE_ARN }}
  CDK_DEFAULT_REGION: us-east-1  
  CDK_DEFAULT_ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}

jobs:
  ci:
    name: Deploy To AWS using CDK
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for aws-actions/configure-aws-credentials
      contents: read # for actions/checkout
    steps:
      - uses: actions/checkout@v4
        with:
          path: '.' # This tells GitHub Actions to checkout into the current directory instead of creating a subdirectory

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Build Lambda
        run: |
          echo "=== DEBUGGING BUILD PROCESS ==="
          echo "1. Current working directory:"
          pwd
          
          echo "2. Root directory contents:"
          ls -la
          
          echo "3. Server directory contents before build:"
          ls -la server/
          
          echo "4. Checking package.json scripts:"
          cat package.json | grep build
          
          echo "5. Server package.json scripts:"
          cat server/package.json | grep build
          
          echo "6. Installing dependencies..."
          npm install
          
          echo "7. Running build command..."
          npm run render-build:lambda
          
          echo "8. Server directory contents after build:"
          ls -la server/
          
          echo "9. Checking if dist was created:"
          ls -la server/dist || echo "dist directory not found"
          
          echo "10. Checking TypeScript config:"
          cat server/tsconfig.json
          
          echo "=== END DEBUGGING ==="

      - name: Build Client
        run: |
          cd client
          npm install
          if [[ ${{ github.ref }} == refs/heads/cdk-dev-* ]]; then
            npm run build:aws  # Use .env.dev-aws for AWS-dev
          else
            npm run build      # Use .env.production for AWS-prod
          fi
          cd ..

      - name: Build Server
        run: |
          npm run render-build:lambda
          mv server/node_modules server/dist/node_modules

      - name: Debug Directory Structure
        run: |
          echo "=== FULL DIRECTORY STRUCTURE ==="
          echo "Root directory:"
          pwd
          echo "\nRoot contents:"
          ls -la
          
          echo "\nServer directory contents:"
          ls -la server/ || echo "No server directory"
          
          echo "\nClient directory contents:"
          ls -la client/ || echo "No client directory"
          
          echo "\nCDK directory contents:"
          ls -la cdk/ || echo "No cdk directory"
          
          if [ -d "server/dist" ]; then
            echo "\nServer/dist contents:"
            ls -la server/dist/
          else
            echo "\nWARNING: server/dist directory not found!"
          fi
          
          if [ -d "client/dist" ]; then
            echo "\nClient/dist contents:"
            ls -la client/dist/
          else
            echo "\nWARNING: client/dist directory not found!"
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: DeployRoleForGitHubSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CDK Stack
        run: | 
          cd cdk
          npm install
          npm run build
          echo "\nVerifying client/dist contents before deployment:"
          ls -la ../client/dist/
          echo "\nVerifying absolute path:"
          realpath ../client/dist
          echo "\nAttempting CDK deploy..."
          if [[ ${{ github.ref }} == refs/heads/cdk-dev-* ]]; then
            echo "Deploying to development environment..."
            echo "Current AWS credentials:"
            aws sts get-caller-identity
            echo "Available stacks:"
            npx cdk ls
            echo "Synthesizing DevCdkStack..."
            npx cdk synth DevCdkStack
            echo "Deploying DevCdkStack..."
            set -x  # This will print each command before executing
            npx cdk deploy DevCdkStack --require-approval never --debug || {
              echo "CDK deploy failed with exit code $?"
              exit 1
            }
          else
            echo "Deploying to production environment..."
            npx cdk deploy CdkStack --require-approval never --debug
          fi

      - name: Sync Client to S3
        run: |

          echo "Current branch: ${{ github.ref }}"
          
          # List all available CloudFormation stacks
          echo "Available CloudFormation stacks:"
          aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE | grep StackName
          
          if [[ ${{ github.ref }} == refs/heads/cdk-dev-* ]]; then
            STACK_NAME="DevCdkStack"
          else
            STACK_NAME="CdkStack"
          fi
          
          echo "Using stack name: $STACK_NAME"
          
          # Check if the stack exists
          if aws cloudformation describe-stacks --stack-name $STACK_NAME &> /dev/null; then
            echo "Stack $STACK_NAME exists"
            
            # Get stack outputs
            echo "Stack outputs:"
            aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output json
            
            # Try different case variations of the output key
            echo "Trying different case variations of the output key..."
            BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' --output text)
            
            if [ -z "$BUCKET_NAME" ]; then
              echo "Trying 'bucketname'..."
              BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`bucketname`].OutputValue' --output text)
            fi
            
            if [ -z "$BUCKET_NAME" ]; then
              echo "Trying 'Bucket'..."
              BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`Bucket`].OutputValue' --output text)
            fi
            
            if [ -z "$BUCKET_NAME" ]; then
              echo "Trying 'bucket'..."
              BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`bucket`].OutputValue' --output text)
            fi
            
            echo "Bucket name from stack output: '$BUCKET_NAME'"
            
            if [ -z "$BUCKET_NAME" ]; then
              echo "ERROR: Bucket name is empty. Checking all stack outputs..."
              
              # Get all outputs
              ALL_OUTPUTS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output json)
              echo "All outputs: $ALL_OUTPUTS"
              
              # List S3 buckets as a fallback
              echo "Available S3 buckets:"
              aws s3 ls
              
              # Try to find a bucket with a name that matches the stack
              echo "Looking for buckets with names containing '$STACK_NAME'..."
              POTENTIAL_BUCKET=$(aws s3 ls | grep -i $STACK_NAME | awk '{print $3}')
              if [ ! -z "$POTENTIAL_BUCKET" ]; then
                echo "Found potential bucket: $POTENTIAL_BUCKET"
                BUCKET_NAME=$POTENTIAL_BUCKET
              else
                echo "No matching bucket found. Looking for any bucket..."
                # Just use the first bucket as a last resort
                POTENTIAL_BUCKET=$(aws s3 ls | head -n 1 | awk '{print $3}')
                if [ ! -z "$POTENTIAL_BUCKET" ]; then
                  echo "Using first available bucket: $POTENTIAL_BUCKET"
                  BUCKET_NAME=$POTENTIAL_BUCKET
                else
                  echo "No buckets found. Cannot proceed."
                  exit 1
                fi
              fi
            fi
            
            echo "Syncing client build to S3 bucket: $BUCKET_NAME"
            aws s3 sync client/dist "s3://$BUCKET_NAME" --delete
          else
            echo "ERROR: Stack $STACK_NAME does not exist"
            exit 1
          fi


      - name: Verify Paths
        run: |
          echo "Current directory:"
          pwd
          echo "\nFull path to client/dist:"
          realpath client/dist
          echo "\nContents of client/dist:"
          ls -la client/dist
          echo "\nAbsolute path check:"
          node -e "console.log(require('path').resolve(__dirname, 'client/dist'))"
